services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.19.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - http.host=0.0.0.0
      - transport.host=0.0.0.0
      - xpack.security.enabled=false
      - cluster.name=elasticsearch
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xmx2048m -Xms2048m"
    volumes:
      - es_data:/usr/share/elasticsearch/data
      - ./docker/elk/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - "9200:9200"
      - "9300:9300"
    ulimits:
      memlock:
        soft: -1
        hard: -1

  logstash:
    image: docker.elastic.co/logstash/logstash:9.1.2
    container_name: logstash
    command: logstash -f /etc/logstash/conf.d/logstash.conf
    volumes:
      - ./docker/elk/logstash.conf:/etc/logstash/conf.d/logstash.conf
      - ./docker/elk/logstash.yml:/usr/share/logstash/config/logstash.yml
    ports:
      - "5000:5000"
    links:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:9.1.2
    container_name: kibana
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - ./docker/elk/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - "5601:5601"
    links:
      - elasticsearch

volumes:
  es_data:

